'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5448
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Profit_WS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Profit_WS.Service1Soap")>  _
    Public Interface Service1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Getcarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function Getcarta() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogEmpleat", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function LogEmpleat(ByVal user As String, ByVal password As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertaComada", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function InsertaComada(ByVal user As String, ByVal password As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/MultiplicaNumeros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function MultiplicaNumeros(ByVal a As Integer, ByVal b As Integer) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits Profit_WS.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of Profit_WS.Service1Soap)
        Implements Profit_WS.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Getcarta() As System.Data.DataTable Implements Profit_WS.Service1Soap.Getcarta
            Return MyBase.Channel.Getcarta
        End Function
        
        Public Function LogEmpleat(ByVal user As String, ByVal password As String) As String Implements Profit_WS.Service1Soap.LogEmpleat
            Return MyBase.Channel.LogEmpleat(user, password)
        End Function
        
        Public Function InsertaComada(ByVal user As String, ByVal password As String) As Boolean Implements Profit_WS.Service1Soap.InsertaComada
            Return MyBase.Channel.InsertaComada(user, password)
        End Function
        
        Public Function MultiplicaNumeros(ByVal a As Integer, ByVal b As Integer) As Integer Implements Profit_WS.Service1Soap.MultiplicaNumeros
            Return MyBase.Channel.MultiplicaNumeros(a, b)
        End Function
    End Class
End Namespace
